pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checking out the code from GitHub..."
                git 'https://github.com/abderahmaneraefat/devops.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh 'docker build -t devops .'
            }
        }
        stage('Run Docker Compose') {
            steps {
                echo "Starting services with Docker Compose..."
                sh 'docker-compose up -d'
            }
        }
        stage('Test Application') {
            steps {
                echo "Running tests on the application..."
                sh 'pytest tests/'
            }
        }
        stage('Push Docker Image') {
            steps {
                echo "Pushing Docker image to Docker Hub..."
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
                    sh 'docker tag my-app my-dockerhub-username/my-app:latest'
                    sh 'docker push my-dockerhub-username/my-app:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                echo "Deploying to Kubernetes..."
                sh 'kubectl apply -f kubernetes.yml'
            }
        }
    }
}
